#!/usr/bin/env bash
#
# \author Zachary Wartell
# \brief See usage() for details.
#

VERSION="0.1.55"


#
# \brief usage() displays usage information for this script.
#
function usage() 
{

DIR=$(dirname $(which $0))

read -r -d '' USAGE << EOF
Usage: $0 [--project-path-suffix <suffix>] [-pps <suffix>]
       $0 [--help][-h]
Version: $VERSION

Options:
        --project-path-suffix, -pps <suffix>  Set the project path suffix.

Purpose:
    This script is used to set up the shell environment for a zjw-pwa-template project.  In particular, it will:
        - Add current path (e.g. ./scripts/) to PATH, 
        - Add current path (e.g. ./scripts/zjwp) to PATH, 
        - Set local shell variable ZJWP_PROJECT_GIT_ROOT to root directory containing .git file.
        - Set other related local shell variables...

Example:
      $ cd scripts
      $ . ./zjwp/zjwp-set-path

Documentation:      
    - See $DIR/docs/zjw-pwa-template-manual.html
EOF

    echo "$USAGE"
}

#
# parse command line arguments
#
PROJECT_PATH_SUFFIX=""
while [ True ]; do
  if [ "$1" = "--project-path-suffix" -o "$1" = "-pps" ]; then      
      PROJECT_PATH_SUFFIX=$2
      shift 2
  elif [ "$1" = "--help" -o "$1" = "-h" ]; then
      usage
      shift 1
      exit 0
  #elif [ "$1" = "--config" -o "$1" = "-c" ]; then
  #    CONFIG=$2
  #    shift 2
  else
      break
  fi
done

PWD=`pwd`

echo -----------------------------------
echo Running \""$PWD/zjwp-set-path"\"

#
# find root .git directory of this project
#
pushd . > /dev/null
GIT_ROOT=`pwd`
while [[ ! -d ".git" ]]; do
    cd ..    
    GIT_ROOT=`pwd`
    #echo here: "$ROOT"
done
popd > /dev/null

echo GIT_ROOT: "$GIT_ROOT"
export ZJWP_PROJECT_GIT_ROOT=$GIT_ROOT
export ZJWP_PROJECT_PATH_SUFFIX=$PROJECT_PATH_SUFFIX
if [ "$PROJECT_PATH_SUFFIX" != "" ]; then
    export ZJWP_PROJECT_NAME=`basename "$ZJWP_PROJECT_GIT_ROOT"`"::"`basename "$ZJWP_PROJECT_PATH_SUFFIX"`
else
    export ZJWP_PROJECT_NAME=`basename "$ZJWP_PROJECT_GIT_ROOT"`
fi

##
## add project name to bash prompt (\ref $PS1)
##
tmp=`mktemp`
echo "$PS1" > $tmp
#echo Before: `cat $tmp`

# \todo code below needs to be generalized further for other bash environments
UN=`uname`
if [[ "$UN" =~ ^MINGW64_NT ]]; then
    #echo "#\\n$\\"
    sed -i -e "s/\\\\n\\$/ [$ZJWP_PROJECT_NAME]\n$/" $tmp
    #echo "After (i):" `cat $tmp`
    export PS1=`cat $tmp`
    echo $PS1
else
    sed -i -e "s/\\\\$\\\n/ [$ZJWP_PROJECT_NAME] $\\\n/" $tmp
    echo "After (ii):" `cat $tmp`
    export PS1=`cat $tmp`
    echo $PS1
    echo $PS1
fi

rm $tmp

ZJWP_PROJECT_SCRIPT_ROOT="$ZJWP_PROJECT_GIT_ROOT/scripts/"

# 9/15/2025: temporarily removed code below:  I've lost track of what this was supposed to do and it looks incorrect to me
# if [[ "$ZJWP_PROJECT_SCRIPT_ROOT" == "$PWD" ]]; then
#     # .. \remark easy case already handled
#     echo .
# else
#     # \remark partial solution
#     ZJWP_PROJECT_SCRIPT_ROOT="$PWD"
# fi

#
# execute project's zjwp-config.sh to set local env. variables
#
. "$ZJWP_PROJECT_SCRIPT_ROOT/zjwp-config.sh"

#
# set $PATH
#
PATH_SUFFIX="$ZJWP_PROJECT_SCRIPT_ROOT/zjwp":"$ZJWP_PROJECT_SCRIPT_ROOT"
export PATH=$PATH:"$PATH_SUFFIX"

echo ZJWP_PROJECT_GIT_ROOT:    $ZJWP_PROJECT_GIT_ROOT
echo ZJWP_PROJECT_SCRIPT_ROOT: $ZJWP_PROJECT_SCRIPT_ROOT
echo ZJWP_PROJECT_NAME:        $ZJWP_PROJECT_NAME
echo PATH_SUFFIX: $PATH_SUFFIX
