#!/usr/bin/env bash

#
# \brief Start npx https-server using a local (unsigned) certificate
#
# References
#   - \ref [r1] https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html
#   - \ref [r2] https://www.man7.org/linux/man-pages//man1/bash.1.html
#   - \ref [r3] 
#


VERSION=1.1.50

##
## Begin "ZJWP bash script header"
##
ZJWP="$(dirname "$0")"
source "$ZJWP/zjwp-core"
zjwp-require node npx sftp
# temporarily removed code below:  test for npm install of http-server requires updates to zjwp-require
#zjwp-require rsync node npx http-server sftp

if [[ ! -v ZJWP_PROJECT_GIT_ROOT ]]; then
    echo Environment variable $ZJWP_PROJECT_GIT_ROOT is not set.  zjwp-set-path must be run from the shell to set zjwp-pwa-template env. variables for this project.
    exit 0;
fi

source "$ZJWP_PROJECT_GIT_ROOT/scripts/zjwp-config.sh"
##
## End "ZJWP bash script header"
##


PORT_PARAM=''
HACK1=''
while [ True ]; do
  if [ "$1" = "--port" -o "$1" = "-p" ]; then
      ALPHA=1
      PORT=$2
      PORT_PARAM="-p $PORT"
      shift 2
  elif [ "$1" = "--hack1" -o "$1" = "-h1" ]; then
      HACK1=1
      shift 1
  #elif [ "$1" = "--config" -o "$1" = "-c" ]; then
  #    CONFIG=$2
  #    shift 2
  else
      break
  fi
done


#pushd "$ZJWP_PROJECT_GIT_ROOT/../zacharywartell-net/cert" > /dev/null
#CERT_DIR_PATH=`pwd`
#popd > /dev/null
UN=`uname`
echo uname: $UN
if [[ -v LOCAL_FAKE_HTTPS_CERT_DIR_PATH ]]; then
  CERT_DIR_PATH=$LOCAL_FAKE_HTTPS_CERT_DIR_PATH
else
  if [[ "$UN" == "MINGW64_NT"* ]]; then
    CERT_DlR_PATH="/c/Users/zwart/Documents/certificates"
    UNS="MINGW64_NT"
  else
    CERT_DIR_PATH="/mnt/c/Users/zwart/Documents/.ssh/certificates"
  fi
fi

#ls -la "$CERT_DIR_PATH"

SERVER_DIR="$ZJWP_PROJECT_GIT_ROOT/$ZJWP_PROJECT_WWW_SUBDIR"
echo $1
if [[ $1 != "" ]]; then
  SERVER_DIR=`realpath $1`
fi

echo PORT:      "$PORT"
echo WWW_ROOT:  "$SERVER_DIR"
echo CERT_DIR_PATH: "$CERT_DIR_PATH"

pushd "$CERT_DIR_PATH" > /dev/null
#pushd "$SERVER_DIR" > /dev/null
echo Running in: `pwd`
#cat "$CERT_DIR_PATH/public_certificate.pem"

TMP=`mktemp`

ls -la "$CERT_DIR_PATH/public_certificate.crt"
ls -la "$CERT_DIR_PATH"


if [[ "$UN" =~ ^CYGWIN_NT ]]; then    
    # Under the cygwin run-time, I assume nodejs is installed via native Windows OS, therefore npx requires passing paths in Windows style path names
    KEY_PATH=$(cygpath -a -w "$CERT_DIR_PATH")
    KEY_PATH="$KEY_PATH\\private_key.pem"

    CERT_PATH=$(cygpath -a -w "$CERT_DIR_PATH")
    CERT_PATH="$CERT_PATH\\public_certificate.crt"
    SERVER_DIR=$(cygpath -a -w "$SERVER_DIR")
else
    KEY_PATH="$CERT_DIR_PATH/private_key.pem"
    CERT_PATH="$CERT_DIR_PATH/public_certificate.crt"
fi

# npx http-server --ssl -C "$CERT_DIR_PATH/public_certificate.crt" -K "$CERT_DIR_PATH/private_key.pem" -c-1 $PORT_PARAM "$SERVER_DIR/" > $TMP 2>&1 &
if [[ -f "$CERT_PATH" && -f "$KEY_PATH" ]]; then
  npx http-server --ssl -C "$CERT_PATH" -K "$KEY_PATH" -c-1 $PORT_PARAM "$SERVER_DIR" > $TMP 2>&1 &
else
  #echo npx http-server --ssl -C "$CERT_DIR_PATH" -K "$KEY_PATH" -K "$CERT_DIR_PATH/private-httpd-server.key" -c-1 $PORT_PARAM "$SERVER_DIR/" 
  if [[ $HACK1 -eq 1 ]]; then
    npx http-server --ssl -C "$CERT_PATH" -K "$CERT_DIR_PATH/private-httpd-server.key" -c-1 $PORT_PARAM "$SERVER_DIR" 
    exit 0
  else
    npx http-server --ssl -C "$CERT_PATH" -K "$CERT_DIR_PATH/private-httpd-server.key" -c-1 $PORT_PARAM "$SERVER_DIR" > $TMP 2>&1 &
  fi  
fi

echo $TMP
tail -f $TMP &
while [ True ]; do
  PORT_LINE=`grep "https://127.0.0.1:*" $TMP`
  if [[ $PORT_LINE != '' ]]; then
    echo "http-server started successfully on $PORT_LINE" 
    break
  fi
  echo waiting...
  sleep 1
done

if [[ "$UN" =~ ^MINGW64_NT || "$UN" =~ ^MSYS_NT ]]; then
  start chrome "$PORT_LINE"
elif [[ "$UN" == "Linux" ]]; then
  chromium "$PORT_LINE" &
else
  # assume wsl  
  cmd.exe /c start chrome "$PORT_LINE"
fi
CERT_DIR_PATH="."


#npx http-server -c-1 -p $PORT "$SERVER_DIR"
#npx http-server -c-1 -p $PORT
#popd > /dev/null
popd > /dev/null

tail -f $TMP
