#!/usr/bin/env bash
#
# @author Zachary Wartell
#
# makefiles are terrible at handling modern files and directory names with spaces, which were
# generally avoided in the pre-GUI, CLI-only days.  makefile workarounds to deal with spaces are all ugly.
# I tried using 'justfiles' but it wasn't worth the hassle of having to install 'just' on every machine I work on.
# Hence, go back to making a bash script; good enough for current needs...

#
# valid TARGETS (mimick makefile)
#
declare -a TARGETS
TARGETS=("push" "revision" "clean" "watch" "build")

MAKE_DIR=$(dirname "$(which "$0")")
MAKE_DIR+="/make"

# 
# env. variable check
#
if [[ ! -v ZJWP_PROJECT_GIT_ROOT ]]; then
	echo Environment Variable 'ZJWP_PROJECT_GIT_ROOT' is missing.
	exit 1
fi

#
# import zjw-pwa config variables
#
CONFIG_FILE="${ZJWP_PROJECT_GIT_ROOT}/scripts/zjwp-config.sh" 
if [[ ! -f "$CONFIG_FILE" ]]; then
	echo Missing file: "$CONFIG_FILE"
	exit 1
fi
source "$CONFIG_FILE"

OUT_DIR="$ZJWP_PROJECT_GIT_ROOT/$ZJWP_PROJECT_WWW_SUBDIR"
SRC_DIR="$ZJWP_PROJECT_GIT_ROOT/$ZJWP_PROJECT_WWW_SUBDIR"

#
# target functions
#

function target_push()
{
    "$MAKE_DIR/embed-revision" "$SRC_DIR"
 	cd ..
    pwd
	git commit -m "Update revision" .
 	echo 'Pushing changes to remote repository...'
 	git push
}

#
function target_revision()
{
    "$MAKE_DIR/embed-revision" "$SRC_DIR"
}

#
function target_clean()
{
	rm -rf "$OUT_DIR"
}

function target_watch()
{
	tsc --watch
}

#
# execute explicit target given as CLI arguement
#
for T in "${TARGETS[@]}"; do 
	if [[ "$1" == "$T" ]]; then
		"target_$1"
	fi
done

