#!/usr/bin/env bash
#
# @author: Zachary Wartell
# @brief: See usage() for details.
#

VERSION="0.1.50"

function usage() {

DIR=$(dirname $(which $0))

read -r -d '' USAGE << EOF
Usage: $0 <SITE_PATH> [--force]
       $0 [--help][-h]
Version: $VERSION

Options:
        --project-path-suffix, -pps <suffix>  Set the project path suffix.

Purpose:
    This script is increments a version number (<integer>.<integer>.<integer>) in:
        \$ZJWP_PROJECT_GIT_ROOT/scripts/revision-info/VERSION.txt
    and maintains a build date in:
        \$ZJWP_PROJECT_GIT_ROOT/scripts/revision-info/BUILDDATE.txt

    The script updates the following files (if they exist) found sub-directories of \$SITE_PATH with the version and build date:
        - HTML files (e.g. index.html, *.html)
        - main.ts, main.js
        - manifest.json
        - package.json
        - PWA service worker .js

    \todo Need to write further details of what this script does.

Example:
    This script is intended to be called from the zjwp makefile or justfile (scripts/make/*

EOF
#Documentation:
#    - See $DIR/docs/zjw-pwa-template-manual.html

    echo "$USAGE"
}

SITE_PATH=""
force=0
#
# parse command line arguments
#
while [ True ]; do
  if [ "$#" -eq 0 ]; then
      usage      
      exit 0
  elif [ "$1" = "--help" -o "$1" = "-h" ]; then
      usage      
      exit 0
  elif [ "$1" = "--force" -o "$1" = "-f" ]; then
      force=1
      shift 2
  else
      SITE_PATH="$1"
      break
  fi
done
echo SITE_PATH:  $SITE_PATH

# If Git hash checksum indicates project files were updated, then bump up the VERSION number and updated the BUILDDATE
# see file://./embed-revision.code-doc.html#VERSION
#
# \todo this conditional test does not quite work correctly, the test generates false positives
HASH=`git show --no-patch --no-notes --pretty='%H'`
OLD_HASH=`cat "$ZJWP_PROJECT_GIT_ROOT/scripts/revision-info/HASH.txt"`
if [[ $HASH != $OLD_HASH || $force ]] then
    echo "Updating revision-info files"

    mkdir -p "$ZJWP_PROJECT_GIT_ROOT/scripts/revision-info/"
    echo $HASH > "$ZJWP_PROJECT_GIT_ROOT/scripts/revision-info/HASH.txt"

    BASE_VERSION=`cat "$ZJWP_PROJECT_GIT_ROOT/scripts/revision-info/BASE_VERSION.txt"`
    VERSION=`cat "$ZJWP_PROJECT_GIT_ROOT/scripts/revision-info/VERSION.txt"`
    echo BASE_VERSION: $BASE_VERSION
    echo VERSION: $VERSION

    #
    # Update VERSION info stored in scripts/revision-info/VERSION.txt, see file://./embed-revision.code-doc.html#VERSION
    #
    PART_1=`echo $VERSION | awk 'BEGIN { FS = "." } ; {print $1}'`
    PART_2=`echo $VERSION | awk 'BEGIN { FS = "." } ; {print $2}'`
    PART_3=`echo $VERSION | awk 'BEGIN { FS = "." } ; {print $3}'`
    echo PARTS: $PART_1 : $PART_2 : $PART_3
    PART_3=$((PART_3 + 1))
    echo $PART_1.$PART_2.$PART_3 > "$ZJWP_PROJECT_GIT_ROOT/scripts/revision-info/VERSION.txt"

    #exit 1;

    #
    # Update various source code and package management files that contain the app revision info (VERSION and BUILDDATE)
    # see file://./embed-revision.code-doc.html#MARKED_FILES
    #
        
    #echo -n 'window["buildDate"] = "' > revision-info/BUILDDATE.txt
    echo `git show --no-patch --no-notes --pretty='%ai'` > "$ZJWP_PROJECT_GIT_ROOT/scripts/revision-info/BUILDDATE.txt"
    #echo -n '";' >> REVISION.txt

    BUILD_DATE=$(cat "$ZJWP_PROJECT_GIT_ROOT/scripts/revision-info/BUILDDATE.txt")
    APP_VERSION=$(cat "$ZJWP_PROJECT_GIT_ROOT/scripts/revision-info/VERSION.txt")

    ##
    ## update HTML file (at maxdepth of 1 to avoid subdirectories and submodules)
    ##
    # - regex:  /<!--BUILDDATE--> [^<]*</<!--BUILDDATE--> ${BUILD_DATE}<
    # - regex:  /<!--APPVERSION-->[^<]*</<!--APPVERSION-->${APP_VERSION}<
    HTML_FILES=`find "$SITE_PATH" -maxdepth 1 -name "index.html" -o -name "*.html"`
    SAVEIFS=$IFS # Save the original IFS
    IFS=$(echo -en "\n\b") # Set IFS to newline and backspace (to handle some edge cases)

    for HTML_FILE in $HTML_FILES; do        
        echo "Updating build date in: $HTML_FILE"
        sed -i -e s/'<!--\s*BUILDDATE\s*-->[^<]*<'/"<!--BUILDDATE-->$BUILD_DATE<"/ "$HTML_FILE"
        sed -i -e s/'<!--\s*APPVERSION\s*-->[^<]*<'/"<!--APPVERSION-->$APP_VERSION<"/ "$HTML_FILE"
    done
    IFS=$SAVEIFS # Restore the original IFS

    #
    # update main.ts
    #
    MAIN_TS=`find "$SITE_PATH" ! -path "*git-modules*" -name "main.ts" -o -name "zjw-ai-journal.ts" `
    if [[ $MAIN_TS != "" ]]; then
        echo "Updating build date in: $MAIN_TS"
        sed -i -e s/'=.*; \/\/BUILDDATE'/"= \"$BUILD_DATE\"; \/\/BUILDDATE"/ $MAIN_TS
        sed -i -e s/'=.*; \/\/APPVERSION'/"= \"$APP_VERSION\"; \/\/APPVERSION"/ $MAIN_TS
    fi

    #
    # update main.js
    #
    MAIN_JS=`find "$SITE_PATH" -name "main.js" -o -name "zjw-ai-journal.js"`
    if [[ $MAIN_JS != "" ]]; then
        sed -i -e s/'=.*; \/\/BUILDDATE'/"= \"$BUILD_DATE\"; \/\/BUILDDATE"/ $MAIN_JS
        sed -i -e s/'=.*; \/\/APPVERSION'/"= \"$APP_VERSION\"; \/\/APPVERSION"/ $MAIN_JS
    fi
    
    #
    # update manifest.json
    #
    if [[ -f "$SITE_PATH/manifest.json" ]]; then
        echo "Updating \"version\" in: $SITE_PATH/manifest.json"
        sed -i -e s/"\"version\"\s*: \".*\""/"\"version\": \"$APP_VERSION\""/ "$SITE_PATH/manifest.json"
    fi
    #cat $SITE_PATH/manifest.json

    #
    # update package.json
    #
    if [[ -f "$SITE_PATH/package.json" ]]; then
        echo "Updating \"version\" in: $SITE_PATH/package.json"
        sed -i -e s/'"version"\s*: ".*"'/"\"version\": \"$APP_VERSION\""/ "$SITE_PATH/package.json"
    fi

    #
    # update PWA service worker
    #
    SERVICE_WORKER=`find "$SITE_PATH" -name "*serviceworker*.js" -o -name "service-worker*.js"`
    if [[ $SERVICE_WORKER != "" ]]; then
        echo 
        echo "Updating \"version\" in: $SERVICE_WORKER"
        sed -i -e s/'VERSION = "v.*"'/"\VERSION = \"v$APP_VERSION\""/ "$SERVICE_WORKER"    
    fi        
fi        